
server:
  port: 8011
  servlet:
    context-path: /@artifactId@
spring:
  application:
    name: @artifactId@
  datasource:
    driver-class-name: net.ucanaccess.jdbc.UcanaccessDriver
    url: jdbc:ucanaccess://${JDBC_URL:src\main\resources\accountsdb.accdb}
    username:
    password:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.HSQLDialect
      ddl-auto: validate
management:
  httpexchanges:
    recording:
      enabled: true
  endpoint:
    health:
      show-details: always
    metrics:
      enabled: true
      export:
        prometheus:
          enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
secret: A31E8C6D5BF7E9A08C6D7E528A4F01B5E26C9D0F387E4A1B5C76D4E7A9081B5A3E28C76D7A08C6D5B7E9A0B4C76D8A4F012E5C6D9A